FROM node:20-alpine
RUN npm install -g typescript ts-node ts-lint
WORKDIR /usr/src/app
COPY ./sih-atellica-qlik-service/package*.json ./
RUN npm install npm -g
RUN npm install
COPY ./sih-atellica-qlik-service .
EXPOSE 8080
CMD ["npm", "run", "docker-dev"]
